const fileSeeds = [
  {
    file_id: '1',
    parent_folder_id: '1',
    user_id: 'user_1',
    file_type: 'image',
    file_url: 'https://s3.amazonaws.com/xyphoto/cat.jpg',
    file_thumbnail_url: 'https://s3.amazonaws.com/xyphoto/cat_thumbnail.jpg',
    size: 3000000,
    width: 1200,
    height: 800,
    tags: ['cat'] ,
    geo: '',
    description: ''
  },
  {
    file_id: '2',
    parent_folder_id: '1',
    user_id: 'user_1',
    file_type: 'image',
    file_url: 'https://s3.amazonaws.com/xyphoto/cat.jpg',
    file_thumbnail_url: 'https://s3.amazonaws.com/xyphoto/cat_thumbnail.jpg',
    size: 2500000,
    width: 500,
    height: 800,
    tags: ['cat'] ,
    geo: '',
    description: ''
  },
  {
    file_id: '3',
    parent_folder_id: '1',
    user_id: 'user_1',
    file_type: 'image',
    file_url: 'https://s3.amazonaws.com/xyphoto/cat.jpg',
    file_thumbnail_url: 'https://s3.amazonaws.com/xyphoto/cat_thumbnail.jpg',
    size: 2340000,
    width: 512,
    height: 300,
    tags: ['cat'] ,
    geo: '',
    description: ''
  },
  {
    file_id: '4',
    parent_folder_id: '1',
    user_id: 'user_1',
    file_type: 'image',
    file_url: 'https://s3.amazonaws.com/xyphoto/cat.jpg',
    file_thumbnail_url: 'https://s3.amazonaws.com/xyphoto/cat_thumbnail.jpg',
    size: 4020000,
    width: 640,
    height: 360,
    tags: ['cat'] ,
    geo: '',
    description: ''
  },
  {
    file_id: '5',
    parent_folder_id: '5',
    user_id: 'user_1',
    file_type: 'image',
    file_url: 'https://s3.amazonaws.com/xyphoto/cat.jpg',
    file_thumbnail_url: 'https://s3.amazonaws.com/xyphoto/cat_thumbnail.jpg',
    size: 1073000,
    width: 960,
    height: 800,
    tags: ['cat'] ,
    geo: '',
    description: ''
  },
  {
    file_id: '6',
    parent_folder_id: '6',
    user_id: 'user_1',
    file_type: 'image',
    file_url: 'https://s3.amazonaws.com/xyphoto/cat.jpg',
    file_thumbnail_url: 'https://s3.amazonaws.com/xyphoto/cat_thumbnail.jpg',
    size: 3400000,
    width: 1080,
    height: 600,
    tags: ['cat'] ,
    geo: '',
    description: ''
  },
  {
    file_id: '7',
    parent_folder_id: '7',
    user_id: 'user_1',
    file_type: 'image',
    file_url: 'https://s3.amazonaws.com/xyphoto/cat.jpg',
    file_thumbnail_url: 'https://s3.amazonaws.com/xyphoto/cat_thumbnail.jpg',
    size: 1200000,
    width: 688,
    height: 530,
    tags: ['cat'] ,
    geo: '',
    description: ''
  },
  {
    file_id: '8',
    parent_folder_id: '8',
    user_id: 'user_1',
    file_type: 'image',
    file_url: 'https://s3.amazonaws.com/xyphoto/cat.jpg',
    file_thumbnail_url: 'https://s3.amazonaws.com/xyphoto/cat_thumbnail.jpg',
    size: 2080000,
    width: 1400,
    height: 800,
    tags: ['cat'] ,
    geo: '',
    description: ''
  },
  {
    file_id: '9',
    parent_folder_id: '9',
    user_id: 'user_1',
    file_type: 'image',
    file_url: 'https://s3.amazonaws.com/xyphoto/cat.jpg',
    file_thumbnail_url: 'https://s3.amazonaws.com/xyphoto/cat_thumbnail.jpg',
    size: 980000,
    width: 500,
    height: 900,
    tags: ['cat'] ,
    geo: '',
    description: ''
  }
];

module.exports = fileSeeds;